### ISSUE TITLE
Test issue - yall seeing this?

### ISSUE THREAD

**Issue by cforee** [remind101/angular-tooltip#14]

**Comment by ejholmes** [comment]
Hi @cforee. We see the issues. This repo is unmaintained by us because:

1. We don't actually use it internally.
2. We're moving away from angular to react.

You might want to try one of the [many forks](https://github.com/remind101/angular-tooltip/network). I'll add a note to the readme.

**Comment by cforee** [comment]
Oh - hey sorry about that.  Accidentally posted a test message to the wrong repo

**Comment by ejholmes** [comment]
No worries :)
